fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    staging: "https://github.com/nanliu/puppet-staging"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql"
  symlinks:
    dcm4chee: "#{source_dir}"
