fixtures:
  repositories:
    stdlib:
        repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
        ref: 4.9.0
    'staging':
        repo: 'https://github.com/nanliu/puppet-staging'
        ref: 1.0.3
    'mysql':
        repo: 'https://github.com/puppetlabs/puppetlabs-mysql'
        ref: 3.6.1
  symlinks:
    dcm4chee: "#{source_dir}"
